export interface CampeonatoType {
	Id: number,
	NombreUrl: string,
	Nombre: string,
	NombreAdmin: string,
	Mail:string,
	Password: string,
	Domicilio: string,
	IdCiudad: number,
	Telefono: string,	
	Celular: string,
	Estado: string,
	TokenResetPwd: string,
	IdGoogle: number,
	PerfilGoogle: string,
	IdLogo: number,
	ImagenLogo: string,
	IdPais: number,
}


export const DefaultCampeonatoType = (): CampeonatoType => ({
	Id: 0,
	NombreUrl: "",
	Nombre: "",
	NombreAdmin: "",
	Mail: "",
	Password: "",
	Domicilio: "",
	IdCiudad: 0,
	Telefono: "",	
	Celular: "",
	Estado: "",
	TokenResetPwd: "",
	IdGoogle: 0,
	PerfilGoogle: "",
	IdLogo: 0,
	ImagenLogo: "",
	IdPais: 0,
});
